version: "3"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: backend
    ports:
      - 5000:5000
    restart: on-failure
    env_file:
      - ./.env
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    restart: on-failure
